---
- name: Install and start the service
  hosts: localhost
  become: yes   # needed for package install and service control

  tasks:
    - name: Installing nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Starting the nginx service
      service:
        name: nginx
        state: started
        enabled: true

